# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 0, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 110, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 130, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 180, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 200, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(250, 110, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 60, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(250, 130, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(250, 150, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 190, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(250, 210, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(250, 250, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(250, 230, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(520, 90, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.okdropres = QtWidgets.QPushButton(self.centralwidget)
        self.okdropres.setGeometry(QtCore.QRect(530, 160, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.okdropres.setFont(font)
        self.okdropres.setObjectName("okdropres")
        self.checkBox_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_13.setGeometry(QtCore.QRect(530, 130, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(530, 110, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.checkBox_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_14.setGeometry(QtCore.QRect(530, 210, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(520, 190, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.checkBox_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_15.setGeometry(QtCore.QRect(530, 240, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(520, 300, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.okdatanorm = QtWidgets.QPushButton(self.centralwidget)
        self.okdatanorm.setGeometry(QtCore.QRect(530, 280, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.okdatanorm.setFont(font)
        self.okdatanorm.setObjectName("okdatanorm")
        self.okw2v = QtWidgets.QPushButton(self.centralwidget)
        self.okw2v.setGeometry(QtCore.QRect(530, 360, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.okw2v.setFont(font)
        self.okw2v.setObjectName("okw2v")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(520, 330, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.w2vname = QtWidgets.QTextEdit(self.centralwidget)
        self.w2vname.setGeometry(QtCore.QRect(560, 330, 161, 21))
        self.w2vname.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.w2vname.setInputMethodHints(QtCore.Qt.ImhNone)
        self.w2vname.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.w2vname.setObjectName("w2vname")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 350, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 380, 251, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(400, 330, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(810, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(810, 210, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.alldatanorm = QtWidgets.QTextEdit(self.centralwidget)
        self.alldatanorm.setGeometry(QtCore.QRect(830, 230, 161, 21))
        self.alldatanorm.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.alldatanorm.setInputMethodHints(QtCore.Qt.ImhNone)
        self.alldatanorm.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.alldatanorm.setObjectName("alldatanorm")
        self.allresultsname = QtWidgets.QTextEdit(self.centralwidget)
        self.allresultsname.setGeometry(QtCore.QRect(830, 310, 161, 21))
        self.allresultsname.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.allresultsname.setInputMethodHints(QtCore.Qt.ImhNone)
        self.allresultsname.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.allresultsname.setObjectName("allresultsname")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(810, 260, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(820, 290, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(820, 340, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.cnnname = QtWidgets.QTextEdit(self.centralwidget)
        self.cnnname.setGeometry(QtCore.QRect(830, 360, 161, 21))
        self.cnnname.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cnnname.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cnnname.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cnnname.setObjectName("cnnname")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(810, 80, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(540, 390, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.twdsets = QtWidgets.QTableWidget(self.centralwidget)
        self.twdsets.setGeometry(QtCore.QRect(810, 100, 341, 101))
        self.twdsets.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.twdsets.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.twdsets.setMidLineWidth(1)
        self.twdsets.setDragEnabled(False)
        self.twdsets.setAlternatingRowColors(True)
        self.twdsets.setRowCount(7)
        self.twdsets.setColumnCount(3)
        self.twdsets.setObjectName("twdsets")
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twdsets.setItem(6, 2, item)
        self.twdsets.horizontalHeader().setVisible(True)
        self.twdsets.horizontalHeader().setCascadingSectionResizes(True)
        self.twdsets.horizontalHeader().setDefaultSectionSize(100)
        self.twdsets.horizontalHeader().setMinimumSectionSize(35)
        self.twdsets.horizontalHeader().setSortIndicatorShown(True)
        self.twdsets.horizontalHeader().setStretchLastSection(True)
        self.twdsets.verticalHeader().setVisible(True)
        self.twdsets.verticalHeader().setCascadingSectionResizes(True)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtconnstr = QtWidgets.QTextEdit(self.centralwidget)
        self.txtconnstr.setGeometry(QtCore.QRect(280, 30, 641, 21))
        self.txtconnstr.setObjectName("txtconnstr")
        self.twclassif = QtWidgets.QTableWidget(self.centralwidget)
        self.twclassif.setGeometry(QtCore.QRect(520, 410, 521, 181))
        self.twclassif.setAlternatingRowColors(True)
        self.twclassif.setRowCount(6)
        self.twclassif.setColumnCount(2)
        self.twclassif.setObjectName("twclassif")
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twclassif.setItem(5, 1, item)
        self.twclassif.horizontalHeader().setDefaultSectionSize(140)
        self.twclassif.horizontalHeader().setMinimumSectionSize(20)
        self.twclassif.horizontalHeader().setStretchLastSection(True)
        self.twclassif.verticalHeader().setVisible(True)
        self.twclassif.verticalHeader().setMinimumSectionSize(7)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 230, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.cntclss = QtWidgets.QTextEdit(self.centralwidget)
        self.cntclss.setGeometry(QtCore.QRect(170, 230, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.cntclss.setFont(font)
        self.cntclss.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cntclss.setObjectName("cntclss")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(10, 260, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.limit = QtWidgets.QTextEdit(self.centralwidget)
        self.limit.setGeometry(QtCore.QRect(180, 260, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.limit.setFont(font)
        self.limit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.limit.setObjectName("limit")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(1060, 210, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(1060, 360, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lstMetrics = QtWidgets.QListWidget(self.centralwidget)
        self.lstMetrics.setGeometry(QtCore.QRect(1060, 240, 91, 81))
        self.lstMetrics.setAlternatingRowColors(True)
        self.lstMetrics.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.lstMetrics.setObjectName("lstMetrics")
        item = QtWidgets.QListWidgetItem()
        self.lstMetrics.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstMetrics.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstMetrics.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstMetrics.addItem(item)
        self.lstngrams = QtWidgets.QListWidget(self.centralwidget)
        self.lstngrams.setGeometry(QtCore.QRect(1060, 390, 91, 91))
        self.lstngrams.setAlternatingRowColors(True)
        self.lstngrams.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.lstngrams.setObjectName("lstngrams")
        item = QtWidgets.QListWidgetItem()
        self.lstngrams.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstngrams.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstngrams.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstngrams.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstngrams.addItem(item)
        self.featAll = QtWidgets.QTextEdit(self.centralwidget)
        self.featAll.setGeometry(QtCore.QRect(390, 270, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.featAll.setFont(font)
        self.featAll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.featAll.setObjectName("featAll")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(270, 270, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.feateach = QtWidgets.QTextEdit(self.centralwidget)
        self.feateach.setGeometry(QtCore.QRect(390, 170, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.feateach.setFont(font)
        self.feateach.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.feateach.setObjectName("feateach")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(270, 170, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.show = QtWidgets.QPushButton(self.centralwidget)
        self.show.setGeometry(QtCore.QRect(270, 370, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.show.setFont(font)
        self.show.setObjectName("show")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(10, 480, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.losspath = QtWidgets.QTextEdit(self.centralwidget)
        self.losspath.setGeometry(QtCore.QRect(230, 510, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.losspath.setFont(font)
        self.losspath.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.losspath.setObjectName("losspath")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(20, 510, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.f1path = QtWidgets.QTextEdit(self.centralwidget)
        self.f1path.setGeometry(QtCore.QRect(230, 540, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.f1path.setFont(font)
        self.f1path.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.f1path.setObjectName("f1path")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(20, 540, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.emb_dim = QtWidgets.QTextEdit(self.centralwidget)
        self.emb_dim.setGeometry(QtCore.QRect(200, 290, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.emb_dim.setFont(font)
        self.emb_dim.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.emb_dim.setObjectName("emb_dim")
        self.w2vdim = QtWidgets.QTextEdit(self.centralwidget)
        self.w2vdim.setGeometry(QtCore.QRect(200, 320, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.w2vdim.setFont(font)
        self.w2vdim.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.w2vdim.setObjectName("w2vdim")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(10, 290, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(10, 320, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(240, 300, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.w2vvectors = QtWidgets.QCheckBox(self.centralwidget)
        self.w2vvectors.setGeometry(QtCore.QRect(240, 320, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.w2vvectors.setFont(font)
        self.w2vvectors.setChecked(False)
        self.w2vvectors.setObjectName("w2vvectors")
        self.train = QtWidgets.QCheckBox(self.centralwidget)
        self.train.setGeometry(QtCore.QRect(240, 340, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.train.setFont(font)
        self.train.setChecked(True)
        self.train.setObjectName("train")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setEnabled(False)
        self.cancel.setGeometry(QtCore.QRect(400, 370, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 410, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.output.setFont(font)
        self.output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SentAnalisys"))
        self.label.setText(_translate("MainWindow", "Оценка качества классификации"))
        self.checkBox.setText(_translate("MainWindow", "Алгоритмы классификации"))
        self.checkBox_2.setText(_translate("MainWindow", "Сверточная нейронная сеть"))
        self.checkBox_3.setText(_translate("MainWindow", "Регулярные выражения"))
        self.label_3.setText(_translate("MainWindow", "Параметры"))
        self.checkBox_4.setText(_translate("MainWindow", "Стемминг"))
        self.checkBox_5.setText(_translate("MainWindow", "Классический"))
        self.label_5.setText(_translate("MainWindow", "Подходы к классификации"))
        self.checkBox_6.setText(_translate("MainWindow", "Word2Vec"))
        self.checkBox_7.setText(_translate("MainWindow", "Сверточная нейронная сеть"))
        self.label_7.setText(_translate("MainWindow", "1. По отдельным наборам данных"))
        self.label_8.setText(_translate("MainWindow", "2. По объединенной выборке"))
        self.checkBox_9.setText(_translate("MainWindow", "Классический"))
        self.checkBox_11.setText(_translate("MainWindow", "Сверточная нейронная сеть"))
        self.checkBox_10.setText(_translate("MainWindow", "Word2Vec"))
        self.label_6.setText(_translate("MainWindow", "Доп. действия"))
        self.label_9.setText(_translate("MainWindow", "1. Очистить таблицы с результатами"))
        self.okdropres.setText(_translate("MainWindow", "OK"))
        self.checkBox_13.setText(_translate("MainWindow", "Сверточная нейронная сеть"))
        self.checkBox_12.setText(_translate("MainWindow", "Классический и Word2Vec"))
        self.label_10.setText(_translate("MainWindow", "1. Сохранение моделей"))
        self.label_11.setText(_translate("MainWindow", "2. Нормализация текста"))
        self.checkBox_14.setText(_translate("MainWindow", "Удалить содержимое"))
        self.label_12.setText(_translate("MainWindow", "2. Таблица с объединенной выборкой"))
        self.checkBox_15.setText(_translate("MainWindow", "Добавить из перечисленных\n"
"в источниках таблиц"))
        self.label_13.setText(_translate("MainWindow", "3. Создать модель Word2Vec"))
        self.okdatanorm.setText(_translate("MainWindow", "OK"))
        self.okw2v.setText(_translate("MainWindow", "OK"))
        self.label_14.setText(_translate("MainWindow", "Имя:"))
        self.w2vname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">w2vmodelFull</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Отчеты"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Лучшие результаты классического подхода"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Лучшие результаты подхода Word2Vec"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Оптимальные параметры"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Топ 5 алгоримтов классифкации"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Оценка нейронной сети (по выборкам)"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Оценка нейронной сети (объединенная выборка)"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Общий случай (лучшие по объединенной выборке)"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Сводная диаграмма качества классификации"))
        self.comboBox.setItemText(8, _translate("MainWindow", "График функции потерь"))
        self.comboBox.setItemText(9, _translate("MainWindow", "График F1-меры"))
        self.start.setText(_translate("MainWindow", "Старт"))
        self.label_16.setText(_translate("MainWindow", "Имена таблиц"))
        self.label_17.setText(_translate("MainWindow", "2. Объединенные выборки"))
        self.alldatanorm.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dsets.all_data_norm</p></body></html>"))
        self.allresultsname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">reports.allresults</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "3. Таблицы с результатами"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>3.1. Классический и word2vec</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "3.2. Сверточные нейронные сети"))
        self.cnnname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">reports.CNNresults</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "1. Таблицы с наборами данных"))
        self.label_22.setText(_translate("MainWindow", "Алгоритмы классификации"))
        item = self.twdsets.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Набор"))
        item = self.twdsets.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Схема.таблица"))
        item = self.twdsets.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Язык"))
        __sortingEnabled = self.twdsets.isSortingEnabled()
        self.twdsets.setSortingEnabled(False)
        item = self.twdsets.item(0, 0)
        item.setText(_translate("MainWindow", "IMDb"))
        item = self.twdsets.item(0, 1)
        item.setText(_translate("MainWindow", "dsets.IMDb"))
        item = self.twdsets.item(0, 2)
        item.setText(_translate("MainWindow", "английский"))
        item = self.twdsets.item(1, 0)
        item.setText(_translate("MainWindow", "eng_amazon_food"))
        item = self.twdsets.item(1, 1)
        item.setText(_translate("MainWindow", "dsets.eng_amazon_food"))
        item = self.twdsets.item(1, 2)
        item.setText(_translate("MainWindow", "английский"))
        item = self.twdsets.item(2, 0)
        item.setText(_translate("MainWindow", "rus_news"))
        item = self.twdsets.item(2, 1)
        item.setText(_translate("MainWindow", "dsets.rus_news"))
        item = self.twdsets.item(2, 2)
        item.setText(_translate("MainWindow", "английский"))
        item = self.twdsets.item(3, 0)
        item.setText(_translate("MainWindow", "rus_rev_books"))
        item = self.twdsets.item(3, 1)
        item.setText(_translate("MainWindow", "dsets.rus_rev_books"))
        item = self.twdsets.item(3, 2)
        item.setText(_translate("MainWindow", "английский"))
        item = self.twdsets.item(4, 0)
        item.setText(_translate("MainWindow", "rus_rev_cameras"))
        item = self.twdsets.item(4, 1)
        item.setText(_translate("MainWindow", "dsets.rus_rev_cameras"))
        item = self.twdsets.item(4, 2)
        item.setText(_translate("MainWindow", "английский"))
        item = self.twdsets.item(5, 0)
        item.setText(_translate("MainWindow", "rus_rev_films"))
        item = self.twdsets.item(5, 1)
        item.setText(_translate("MainWindow", "dsets.rus_rev_films"))
        item = self.twdsets.item(5, 2)
        item.setText(_translate("MainWindow", "английский"))
        item = self.twdsets.item(6, 0)
        item.setText(_translate("MainWindow", "rus_twitter_full"))
        item = self.twdsets.item(6, 1)
        item.setText(_translate("MainWindow", "dsets.rus_twitter_full"))
        item = self.twdsets.item(6, 2)
        item.setText(_translate("MainWindow", "английский"))
        self.twdsets.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Строка подлкючения к базе данных:"))
        self.txtconnstr.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dbname=\'DegreeProject\' user=\'ALECIO\' password=\'ALECIO\' host=\'localhost\' port=\'5432\'</p></body></html>"))
        item = self.twclassif.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Алгоритм"))
        item = self.twclassif.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Параметры"))
        __sortingEnabled = self.twclassif.isSortingEnabled()
        self.twclassif.setSortingEnabled(False)
        item = self.twclassif.item(0, 0)
        item.setText(_translate("MainWindow", "GaussianNB"))
        item = self.twclassif.item(0, 1)
        item.setText(_translate("MainWindow", "Все"))
        item = self.twclassif.item(1, 0)
        item.setText(_translate("MainWindow", "AdaBoostClassifier"))
        item = self.twclassif.item(1, 1)
        item.setText(_translate("MainWindow", "Все"))
        item = self.twclassif.item(2, 0)
        item.setText(_translate("MainWindow", "DecisionTreeClassifier"))
        item = self.twclassif.item(2, 1)
        item.setText(_translate("MainWindow", "Все"))
        item = self.twclassif.item(3, 0)
        item.setText(_translate("MainWindow", "SVM"))
        item = self.twclassif.item(3, 1)
        item.setText(_translate("MainWindow", "Все"))
        item = self.twclassif.item(4, 0)
        item.setText(_translate("MainWindow", "LogisticRegressionCV"))
        item = self.twclassif.item(4, 1)
        item.setText(_translate("MainWindow", "Все"))
        item = self.twclassif.item(5, 0)
        item.setText(_translate("MainWindow", "RandomForestClassifier"))
        item = self.twclassif.item(5, 1)
        item.setText(_translate("MainWindow", "Все"))
        self.twclassif.setSortingEnabled(__sortingEnabled)
        self.label_23.setText(_translate("MainWindow", "3. Количество классов"))
        self.cntclss.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "4. Лимит строк выборки"))
        self.limit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">25000</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "Метрики"))
        self.label_26.setText(_translate("MainWindow", "N-граммы"))
        __sortingEnabled = self.lstMetrics.isSortingEnabled()
        self.lstMetrics.setSortingEnabled(False)
        item = self.lstMetrics.item(0)
        item.setText(_translate("MainWindow", "TF"))
        item = self.lstMetrics.item(1)
        item.setText(_translate("MainWindow", "FP"))
        item = self.lstMetrics.item(2)
        item.setText(_translate("MainWindow", "TFIDF"))
        item = self.lstMetrics.item(3)
        item.setText(_translate("MainWindow", "deltaTFIDF"))
        self.lstMetrics.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lstngrams.isSortingEnabled()
        self.lstngrams.setSortingEnabled(False)
        item = self.lstngrams.item(0)
        item.setText(_translate("MainWindow", "BOW"))
        item = self.lstngrams.item(1)
        item.setText(_translate("MainWindow", "BG"))
        item = self.lstngrams.item(2)
        item.setText(_translate("MainWindow", "TG"))
        item = self.lstngrams.item(3)
        item.setText(_translate("MainWindow", "BOW_BG"))
        item = self.lstngrams.item(4)
        item.setText(_translate("MainWindow", "BOW_BG_TG"))
        self.lstngrams.setSortingEnabled(__sortingEnabled)
        self.featAll.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">35000</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "Число признаков"))
        self.feateach.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5000</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "Число признаков"))
        self.show.setText(_translate("MainWindow", "Показать"))
        self.label_29.setText(_translate("MainWindow", "Пути до истории сети (-ей)"))
        self.losspath.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">./NN/History/trainHistDic3</p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "1. Просмотр функции потерь"))
        self.f1path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">./NN/History/trainHistDic1, ./NN/History/trainHistDic2, ./NN/History/trainHistDic3</p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p>2. График F1-меры по</p><p>    нескольким сетям</p></body></html>"))
        self.emb_dim.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">300</p></body></html>"))
        self.w2vdim.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">300</p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "5. Размерность вектора сети"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p>6. Размерность вектора w2v</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p>7. Векторный слой сети</p></body></html>"))
        self.w2vvectors.setText(_translate("MainWindow", "Векторы word2vec"))
        self.train.setText(_translate("MainWindow", "Обучение"))
        self.cancel.setText(_translate("MainWindow", "Отмена"))
        self.output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

